name: continuous-integration

on:
  push:
    branches:
      - main
      - develop
  pull_request:

jobs:
#  lint:
#    runs-on: ubuntu-20.04
#    steps:
#      -
#        name: Checkout
#        uses: actions/checkout@v2.3.4
#
#      -
#        name: Lint code
#        uses: golangci/golangci-lint-action@v2.5.2

  test:
    runs-on: ubuntu-20.04
    steps:
      -
        name: Checkout
        uses: actions/checkout@v2.3.4

      -
        name: Setup go
        uses: actions/setup-go@v2.1.4
        with:
          go-version: 1.17.2

      -
        name: Cache Go modules
        uses: actions/cache@v2
        with:
          path: |
            ~/.cache/go-build
            ~/go/pkg/mod
          key: ${{ runner.os }}-go-${{ hashFiles('**/go.sum') }}
          restore-keys: |
            ${{ runner.os }}-go-

      -
        name: Test and Benchmark
        run: |
          go test --bench --benchmem -v
          go vet

  build:
    name: build (${{ matrix.GOOSARCH }})
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        GOOSARCH:
          - linux/amd64
          - linux/arm64
          - darwin/amd64
          - darwin/arm64
          - windows/amd64
          - windows/arm64
    steps:
      -
        name: Get GOOS and GOARCH
        run: |
          GOOSARCH=${{matrix.goosarch}}
          GOOS=${GOOSARCH%/*}
          GOARCH=${GOOSARCH#*/}
          BINARY_NAME=${{github.repository}}-$GOOS-$GOARCH
          echo "BINARY_NAME=$BINARY_NAME" >> $GITHUB_ENV
          echo "GOOS=$GOOS" >> $GITHUB_ENV
          echo "GOARCH=$GOARCH" >> $GITHUB_ENV

      -
        name: Checkout
        uses: actions/checkout@v2.3.4

      -
        name: Setup go
        uses: actions/setup-go@v2.1.4
        with:
          go-version: 1.17.2

      -
        name: Cache Go modules
        uses: actions/cache@v2
        with:
          path: |
            ~/.cache/go-build
            ~/go/pkg/mod
          key: ${{ runner.os }}-go-${{ hashFiles('**/go.sum') }}
          restore-keys: |
            ${{ runner.os }}-go-

      -
        name: Build binary
        run: |
          go build -o $BINARY_NAME
