name: continuous-integration

on:
  push:
  pull_request:

jobs:
  lint:
    runs-on: ubuntu-20.04
    steps:
      -
        name: Checkout
        uses: actions/checkout@v2.3.4

      -
        name: Lint code
        uses: golangci/golangci-lint-action@v2.5.2

  test:
    runs-on: ubuntu-20.04
    steps:
      -
        name: Checkout
        uses: actions/checkout@v2.3.4

      -
        name: Setup go
        uses: actions/setup-go@v2.1.4
        with:
          go-version: 1.17.2

      -
        name: Cache Go modules
        uses: actions/cache@v2
        with:
          path: |
            ~/.cache/go-build
            ~/go/pkg/mod
          key: ${{ runner.os }}-go-${{ hashFiles('**/go.sum') }}
          restore-keys: |
            ${{ runner.os }}-go-

      -
        name: Test and Benchmark
        run: go test --bench --benchmem -v
