name: release

on:
  push:
    branches:
      - main
      - release-*
  pull_request:

jobs:
  verify-base-image:
    runs-on: ubuntu-latest
    steps:
      -
        name: Checkout
        uses: actions/checkout@v2.3.4

      -
        name: Install cosign
        uses: sigstore/cosign-installer@v1.2.0

      -
        name: Verify base image
        run: |
          cosign dockerfile verify \
            -base-image-only \
            -key https://raw.githubusercontent.com/GoogleContainerTools/distroless/main/cosign.pub \
            Dockerfile

  build-images:
    runs-on: ubuntu-latest
    needs: verify-base-image
    environment: release
    steps:
      -
        name: Checkout
        uses: actions/checkout@v2.3.4

      -
        name: Install cosign
        uses: sigstore/cosign-installer@v1.2.0

      -
        name: Docker meta
        id: docker_meta
        uses: docker/metadata-action@v3.5.0
        with:
          images: |
            ghcr.io/${{ github.repository }}
          flavor: |
            latest=true
          tags: |
            type=sha
            type=semver,pattern={{version}}
            type=semver,pattern={{major}}.{{minor}}
            type=semver,pattern={{major}}

      -
        name: Set up Docker Buildx
        id: buildx
        uses: docker/setup-buildx-action@v1.6.0
        with:
          install: true

      -
        name: Login to GitHub Container Registry
        uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GITHUB_TOKEN }}

      -
        name: Build
        uses: docker/build-push-action@v2.7.0
        id: build
        with:
          push: true
          # platforms: linux/amd64,linux/arm64
          builder: ${{ steps.buildx.outputs.name }}
          tags: ${{ steps.docker_meta.outputs.tags }}
          labels: ${{ steps.docker_meta.outputs.labels }}
          cache-from: type=gha
          cache-to: type=gha

      -
        name: Sign image
        env:
          COSIGN_PASSWORD: ${{ secrets.COSIGN_PASSWORD }}
        run: |
          echo "${{ secrets.COSIGN_KEY }}" > cosign.key
          cosign sign -key cosign.key ghcr.io/${{ github.repository }}@${{ steps.build.outputs.digest }}

      -
        name: Verify image
        run: |
          cosign verify -key tools/release-cosign.pub ghcr.io/${{ github.repository }}@${{ steps.build.outputs.digest }}
